### ISSUE TITLE
Sorting C++

### ISSUE THREAD

**Issue by ericward-noaa** [eric-ward/getais#1]
Currently have lines 188-190 of parseCSV.cpp commented out -- need to work with olin on sorting function

**Comment by olin-feist** [comment]
Rcpp uses the gnu C++11 standard namespace which had an issue with the signed and unsigned variables in the sorting function I made. I made the variables unsigned which fixed the compiler warning. However the code no longer uses sorts the csv so there shouldn't be any further issues.
